<?php

/**
 * CorePlaylistsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CorePlaylistsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CorePlaylistsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CorePlaylists');
    }
}