<?php

/**
 * CoreAlbumsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CoreAlbumsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CoreAlbumsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CoreAlbums');
    }
}