<?php

/**
 * CoreTracksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CoreTracksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CoreTracksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CoreTracks');
    }

    /**
     * Fetch the most recently added tracks
     *
     * @return DoctrineResultSet
     **/
    public static function fetchRecent($limit = 10)
    {
      return self::getInstance()->createQuery('ct')->
        orderBy('ct.DateAddedStamp desc')->
        limit($limit)->
        execute();
    }
}
