<?php

/**
 * CorePlaylistEntriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CorePlaylistEntriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CorePlaylistEntriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CorePlaylistEntries');
    }
}