<?php

/**
 * PlayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Play');
    }
}