<?php

/**
 * TracksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TracksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TracksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tracks');
    }
}